FROM node:10-alpine as bld
WORKDIR /app
COPY package*.json /app
RUN npm install

FROM node:10-alpine as dlv
ENV PATH /app/node_modules/.bin:$PATH
WORKDIR /usr/src/app
COPY --from=bld /app/node_modules /app/node_modules
COPY . .
CMD [ "node", "server.js" ]
